Project:
  Name: "Computer8Bit"
  Description: "8-bit Computer From Scratch using Logic Gates"

Version:
  # Main version; any change requires a new version
  MainVersion: "1.74.0.1086"

Components:
  Compiler  : "1.21.0.1024"
  Emulator  : "1.6.0.1006"
  Inspector : "1.1.0.1001"
  Flasher   : "1.8.1.1009"
  7Segment  : "1.4.0.1005"
  ISA       : "1.37.0.1043"
  Document  : "1.28.1.1036"
