Project:
  Name: "Computer8Bit"
  Description: "8-bit Computer From Scratch using Logic Gates"
  
Version:
  # Main version; any change requires a new version
  MainVersion: "1.71.0.1083"
  
Components:
  Compiler  : "1.20.0.1023"
  Emulator  : "1.5.0.1005"
  Inspector : "1.1.0.1001"
  Flasher   : "1.8.1.1009"
  7Segment  : "1.4.0.1005"
  ISA       : "1.34.1.1040"
  Document  : "1.26.0.1033"
