import os
import importlib
import glob
import logging
from dataclasses import dataclass, field
from typing import Dict, List

import MicrocodeConfig

UCODE_0 = MicrocodeConfig.UCODE_0
UCODE_1 = MicrocodeConfig.UCODE_1
UCODE_2 = MicrocodeConfig.UCODE_2
UCODE_ORDER = [UCODE_0, UCODE_1, UCODE_2]
OUTPUT_ROWS_PER_CHIP = 8
EXPECTED_OUTPUT_ROW_COUNT = len(UCODE_ORDER) * OUTPUT_ROWS_PER_CHIP
EXPECTED_INPUT_ADDRESS_ROW_COUNT = 15

MICRO_CODE_MAP_FILE = os.path.join("out", "microCodeMap.txt")
LOGGER = logging.getLogger(__name__)


@dataclass
class ParsedMicroInstructionMatrix:
    InputSignals: List[str] = field(default_factory=list)
    OutputSignalsByChip: Dict[str, List[str]] = field(
        default_factory=lambda: {chipName: [] for chipName in UCODE_ORDER}
    )


@dataclass
class ParsedInstructionData:
    InstructionName: str
    AddressMatrix: List[List[str]] = field(default_factory=list)
    OutputMatrixByChip: Dict[str, List[List[str]]] = field(
        default_factory=lambda: {chipName: [] for chipName in UCODE_ORDER}
    )
    MicroInstructionMatrix: ParsedMicroInstructionMatrix = field(
        default_factory=ParsedMicroInstructionMatrix
    )


@dataclass
class GeneratedMicrocodeResult:
    MicrocodeByChip: Dict[str, List[int]]
    LastMicroInstructionMatrix: ParsedMicroInstructionMatrix


class ParseInstructions:
    def __init__(self):
        """
        Load all autogenerated instruction modules from the autogen output directory.
        The modules are imported, sorted, and stored so later stages can parse
        them into structured address and output matrices.
        """
        self.InsObjects = []
        autogenDir = os.path.join(os.path.dirname(__file__), "out", "autogen")
        autogenFiles = glob.glob(os.path.join(autogenDir, "Autogen_*.py"))

        for filePath in sorted(autogenFiles):
            moduleFilename = os.path.basename(filePath)
            moduleName = moduleFilename[:-3]

            try:
                module = importlib.import_module(f"out.autogen.{moduleName}")
                self.InsObjects.append(module)
            except ImportError as error:
                LOGGER.error(f"Failed to import {moduleName}: {error}")

        LOGGER.info(f"Total autogen instructions imported: {len(self.InsObjects)}")

        self.InsObjects.sort(key=lambda item: item.__name__)
        self.InstructionParsedData: Dict[str, ParsedInstructionData] = {}


    def ValidateParsedInstructionShape(self, parsedInstruction: ParsedInstructionData):
        """
        Validate that one parsed instruction has the exact row shape expected by
        the current hardware layout. This includes fixed input-row count and
        fixed eight-row output blocks for each microcode chip.
        """
        instructionName = parsedInstruction.InstructionName
        if len(parsedInstruction.AddressMatrix) != EXPECTED_INPUT_ADDRESS_ROW_COUNT:
            raise Exception(
                f"ERROR: Instruction '{instructionName}' must contain exactly "
                f"{EXPECTED_INPUT_ADDRESS_ROW_COUNT} input rows, found {len(parsedInstruction.AddressMatrix)}."
            )

        totalOutputRows = 0
        for chipName in UCODE_ORDER:
            chipRowCount = len(parsedInstruction.OutputMatrixByChip[chipName])
            if chipRowCount != OUTPUT_ROWS_PER_CHIP:
                raise Exception(
                    f"ERROR: Instruction '{instructionName}' must contain exactly "
                    f"{OUTPUT_ROWS_PER_CHIP} output rows for chip '{chipName}', found {chipRowCount}."
                )
            totalOutputRows += chipRowCount

            outputSignalCount = len(parsedInstruction.MicroInstructionMatrix.OutputSignalsByChip[chipName])
            if outputSignalCount != OUTPUT_ROWS_PER_CHIP:
                raise Exception(
                    f"ERROR: Instruction '{instructionName}' has mismatched output signal names for chip "
                    f"'{chipName}'. Expected {OUTPUT_ROWS_PER_CHIP}, found {outputSignalCount}."
                )

        if totalOutputRows != EXPECTED_OUTPUT_ROW_COUNT:
            raise Exception(
                f"ERROR: Instruction '{instructionName}' must contain exactly "
                f"{EXPECTED_OUTPUT_ROW_COUNT} total output rows, found {totalOutputRows}."
            )


    def ParseEachInstruction(self):
        """
        Parse each autogenerated instruction module into typed in-memory data.
        The parser separates input rows, chip-grouped output rows, and signal
        names so later stages can build address/data maps deterministically.
        """
        for ins in self.InsObjects:
            textIns: str = ins.INS
            lines = textIns.split("\n")

            instructionName = None
            for line in lines:
                if "INSTRUCTION:" in line:
                    instructionName = line.split(":")[-1].strip()
                    break

            if instructionName is None:
                raise Exception(f"ERROR: Missing INSTRUCTION declaration in autogen instruction module '{ins.__file__}'.")
            parsedInstruction = ParsedInstructionData(InstructionName=instructionName)
            outCount = 0
            chipCount = 0
            for line in lines:
                lineSplit = [item.strip() for item in line.split("|") if item.strip()]
                if len(lineSplit) == 0:
                    continue

                if lineSplit[0] == "I":
                    parsedInstruction.AddressMatrix.append(lineSplit[2:])
                    parsedInstruction.MicroInstructionMatrix.InputSignals.append(lineSplit[1])

                elif lineSplit[0] == "O":
                    if chipCount >= len(UCODE_ORDER):
                        raise Exception(
                            f"ERROR: Instruction '{instructionName}' contains more than "
                            f"{EXPECTED_OUTPUT_ROW_COUNT} output rows."
                        )

                    chipName = UCODE_ORDER[chipCount]
                    parsedInstruction.OutputMatrixByChip[chipName].append(lineSplit[2:])
                    parsedInstruction.MicroInstructionMatrix.OutputSignalsByChip[chipName].append(lineSplit[1])

                    outCount += 1
                    if outCount == OUTPUT_ROWS_PER_CHIP:
                        chipCount += 1
                        outCount = 0

            self.ValidateParsedInstructionShape(parsedInstruction)
            self.InstructionParsedData[instructionName] = parsedInstruction


    def ExpandAddressColumn(self, bitColumn: List[str]) -> List[int]:
        """
        Expand one address column into all concrete addresses it represents.
        Literal `0` and `1` bits are fixed, while any other symbol is treated
        as a don't-care bit and generates all matching address combinations.
        """
        possibleValues: List[int] = []
        maxValue = pow(2, len(bitColumn))

        for candidateValue in range(maxValue):
            resolvedValue = candidateValue
            for bitIndex, bitValue in enumerate(bitColumn):
                if bitValue in ["1", "0"]:
                    resolvedValue = resolvedValue & ~(1 << bitIndex)
                    resolvedValue = resolvedValue | (int(bitValue) << bitIndex)
            if resolvedValue not in possibleValues:
                possibleValues.append(resolvedValue)
        return possibleValues


    def EncodeDataColumn(self, bitColumn: List[str], chipName: str = "") -> int:
        """
        Convert one output bit column into the final byte value written to ROM.
        Only explicit `1` bits contribute to the encoded value; all other
        symbols are treated as inactive for the generated data byte.
        
        YAML MicrocodeChipsPinMap defines exact pin order (IO0-IO7), so we use
        the bit column as-is without any transformation.
        """
        encodedValue = 0
        for bitIndex, bitValue in enumerate(bitColumn):
            if bitValue == "1":
                encodedValue = encodedValue | (1 << bitIndex)
        return encodedValue


    def TransposeMatrix(self, matrix: List[List[str]]) -> List[List[str]]:
        """
        Transpose a row-major instruction matrix into column-major form.
        The generator works column by column because each column represents
        one micro-instruction time step across all participating signals.
        """
        transposedMatrix: List[List[str]] = []
        for columnIndex in range(len(matrix[0])):
            columnValues: List[str] = []
            for row in matrix:
                columnValues.append(row[columnIndex])
            transposedMatrix.append(columnValues)
        return transposedMatrix


    def CreateEmptyMicrocodeMatrix(self) -> Dict[str, List[int]]:
        """Create zero-filled EEPROM images for all configured microcode chips."""
        microcodeMatrix = {UCODE_0: [], UCODE_1: [], UCODE_2: []}
        microcodeSize = 32768
        for chipName in microcodeMatrix:
            for _ in range(microcodeSize):
                microcodeMatrix[chipName].append(0)
        return microcodeMatrix


    def GenerateAddressDataMap(self) -> GeneratedMicrocodeResult:
        """
        Expand parsed instruction tables into full EEPROM address/data images.
        Each instruction column is converted into concrete addresses and byte
        values, then written into per-chip microcode buffers and map output.
        """
        microcodeMatrix = self.CreateEmptyMicrocodeMatrix()
        lastMicroInstructionMatrix = None

        if os.path.exists(MICRO_CODE_MAP_FILE):
            os.remove(MICRO_CODE_MAP_FILE)

        if not os.path.exists("out"):
            os.mkdir("out")

        totalInstructions = len(self.InstructionParsedData)

        with open(MICRO_CODE_MAP_FILE, "w") as mapFilePointer:
            doneCount = 0
            for instruction in self.InstructionParsedData:
                percent = (doneCount / totalInstructions) * 100
                barLength = 40
                filledLength = int(barLength * percent // 100)
                bar = '#' * filledLength + '-' * (barLength - filledLength)
                print(
                    f"   Processing: {instruction:<8} "
                    f"Overall Progress: [{bar}] {percent:6.2f}%{' ' * 40}",
                    end="\r"
                )
                parsedInstruction = self.InstructionParsedData[instruction]
                addressColumns = self.TransposeMatrix(parsedInstruction.AddressMatrix)
                lastMicroInstructionMatrix = parsedInstruction.MicroInstructionMatrix

                for chipName in microcodeMatrix:
                    dataColumns = self.TransposeMatrix(parsedInstruction.OutputMatrixByChip[chipName])

                    mapFilePointer.write(f"\n\nInstruction: {instruction}; Chip: {chipName}\n")
                    mapFilePointer.write(f"------------------------------------------------------------------------------\n")
                    mapFilePointer.write(f"                                   |       |  uu f ssss iiii iiii |  iiii iiii\n")
                    mapFilePointer.write(f"                           Address |  Val  |  nn l qqqq nnnn nnnn |  oooo oooo\n")
                    mapFilePointer.write(f"                                   |       |  01 g 3210 0123 4567 |  7654 3210\n")
                    mapFilePointer.write(f"------------------------------------------------------------------------------\n")
                    mapIndex = 1
                    for columnIndex, addressColumn in enumerate(addressColumns):
                        addresses = self.ExpandAddressColumn(addressColumn)
                        value = self.EncodeDataColumn(dataColumns[columnIndex], chipName)
                        for address in addresses:
                            microcodeMatrix[chipName][address] = value
                            mapFilePointer.write(f"chip_{chipName}_ins_{instruction.lower()}_{mapIndex:04d} :: 0x{address:04x} => 0x{value:02x} //")
                            strAdd = str(f"{address:015b}")
                            strVal = str(f"{value:08b}")
                            mapFilePointer.write(f" {strAdd[13:15]}_{strAdd[12:13]}_{strAdd[8:12]}_{strAdd[4:8]}.{strAdd[0:4]} :: {strVal[:4]}.{strVal[4:8]}\n")
                            mapIndex += 1

                doneCount += 1
                print(f"Completed: {instruction:<8}{' ' * 80}")

            print(f"{' ' * 150}")

        return GeneratedMicrocodeResult(
            MicrocodeByChip=microcodeMatrix,
            LastMicroInstructionMatrix=lastMicroInstructionMatrix
        )



if __name__ == "__main__":
    parser = ParseInstructions()
    parser.ParseEachInstruction()
    parser.GenerateAddressDataMap()

