# MicroCodeConfig.yaml
# This file defines the instruction set and maps signal names to their
# respective 4-bit control codes for InputControl and OutputControl.
# It also includes extra control signals and virtual pin definitions.

InsConfig:
  Instructions:
    - NOP
    - OUT
    - HLT
    - ADD
    - SUB
    - INC
    - DEC
    - LDI
    - LDM
    - SAV
    - JMP
    - JMZ
    - JNZ
    - JMC
    - MOV
    - AND
    - OR
    - XOR
    - NOT
    - CMP
    - CMI
    - RST

PinConfig:
  InputControl:
    rAI  : 0b0000
    rBI  : 0b0001
    rCI  : 0b0010
    rDI  : 0b0011
    PCLI : 0b0100
    PCHI : 0b0101
    MdI  : 0b0110
    MeI  : 0b0111
    IRI  : 0b1000
    T1I  : 0b1001
    T2I  : 0b1010
    Seg7E: 0b1011
    SpL  : 0b1100
    RESRV: 0b1111 # Reserved if no Pin need to be enabled
  OutputControl:
    rAO  : 0b0000
    rBO  : 0b0001
    rCO  : 0b0010
    rDO  : 0b0011
    RomO : 0b0100
    SpO  : 0b0101
    MeO  : 0b0110
    AdSuO: 0b0111
    OrO  : 0b1000
    AndO : 0b1001
    XorO : 0b1010
    FlgU : 0b1011
    PCO  : 0b1100
    SqR  : 0b1101
    RESRV: 0b1111 # Reserved if no Pin need to be enabled
  Extra:
    PCL  : null
    PCC  : null
    SpC  : null
    SpUd : null
    AdSu : null
    Cin  : null
    FlSe0: null
    FlSe1: null
    FlSe2: null
    HLT  : null

VirtualPins:
  InputControlPins:
    ViIn0: null
    ViIn1: null
    ViIn2: null
    ViIn3: null
  OutputControlPins:
    ViOt0: null
    ViOt1: null
    ViOt2: null
    ViOt3: null
