# MicroCodeConfig.yaml
# This file defines the instruction set and maps signal names to their
# respective 4-bit control codes for InputControl and OutputControl.
# It also includes extra control signals and virtual pin definitions.

InsConfig:
  Instructions:
    - NOP
    - OUT
    - HLT
    - ADD
    - SUB
    - INC
    - DEC
    - LDI
    - LDM
    - SAV
    - JMP
    - JMZ
    - JNZ
    - JMC
    - MOV
    - AND
    - OR
    - XOR
    - NOT
    - CMP
    - CMI
    - RST

PinConfig:
  InputControl:
    rAI  : 0b1111
    rBI  : 0b1110
    rCI  : 0b1101
    rDI  : 0b1100
    PCLI : 0b1011
    PCHI : 0b1010
    MdI  : 0b1001
    MeI  : 0b1000
    IRI  : 0b1001
    T1I  : 0b0110
    T2I  : 0b0101
    Seg7E: 0b0100
  OutputControl:
    rAO  : 0b1111
    rBO  : 0b1110
    rCO  : 0b1101
    rDO  : 0b1100
    RomO : 0b1011
    SpO  : 0b1010
    MeO  : 0b1001
    AdSuO: 0b1000
    OrO  : 0b0111
    AndO : 0b0110
    XorO : 0b0101
  Extra:
    PCL  : null
    PCC  : null
    SpC  : null
    SpUd : null
    SpL  : null
    SqR  : null
    AdSu : null
    Cin  : null
    CmpO : null
    FlSe0: null
    FlSe1: null
    FlSe2: null
    HLT  : null

VirtualPins:
  InputControlPins:
    ViIn0: null
    ViIn1: null
    ViIn2: null
    ViIn3: null
  OutputControlPins:
    ViOt0: null
    ViOt1: null
    ViOt2: null
    ViOt3: null
